CREATE TABLE "public"."configuration"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    "uid"          uuid                                        NOT NULL DEFAULT uuid_generate_v4(),
    "created_time" timestamptz(6) NOT NULL,
    "created_by"   varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
    "updated_time" timestamptz(6),
    "updated_by"   varchar(100) COLLATE "pg_catalog"."default",
    "deleted_time" timestamptz(6),
    "deleted_by"   varchar(100) COLLATE "pg_catalog"."default",
    "key"          varchar(255)                                NOT NULL,
    "value"        varchar(255),
    "description"  varchar(255),
    "platform"     varchar(255)
);

CREATE
INDEX "index_configuration_id" ON "public"."configuration" (
  "id",
  "key"
);
